<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div>
<h1>FALSCHI SIIITE!!!!!!</h1>
<form method="POST">
  <label for="uname">Username:</label><br>
  <input type="text" id="fname" name="fname"><br>
  <label for="pword">Password:</label><br>
  <input type="password" id="lname" name="lname">
  <br>
  <br>
  <input type="submit" value="Log In">
</form>

<br>

<input type="button" value="Sign Up">


</div>

