<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div>

<form action="/action_page.php">
  <label for="fname">Username:</label><br>
  <input type="text" id="uname" name="uname"><br>
  <label for="lname">Password:</label><br>
  <input type="password" id="pword" name="pword"><br><br>
  <input type="submit" value="Log In">
</form>

<br>

<input type="button" value="Sign Up">


</div>
